### ISSUE TITLE
Can not control tunable inner

### ISSUE THREAD

**Issue by kasteleman** [athombv/node-homey-meshdriver#39] opened 2017-11-03 20:27 UTC
The capabilities don't get registered automatic.

I have to add the following code to control onoff and dim:

		if (this.hasCapability('onoff')) {
			this.registerCapability('onoff', 'genOnOff', {
				getOpts: {
					getOnStart: true,
				},
			});
		}

		if (this.hasCapability('dim')) {
			this.registerCapability('dim', 'genLevelCtrl', {
				getOpts: {
					getOnStart: true,
				},
			});
		}

The registerMultipleCapabilityListener() { light_temperature: 1 } { light_temperature: {} } never runs, whereas it does for a tunable GU10
Firmware of both GU10 and the E27 are the same (checked by INNR).

**Comment by RobinBol** [comment] 2017-11-06 09:07
You forget to call the `super.onMeshInit()` in the tunable_bulb/device.js, hence the super 'constructor' will not run and will not register the necessary capabilities. Best is to remove all code in tunable_bulb/device.js, similar to tunable_gu10/device.js.

**Comment by kasteleman** [comment] 2017-11-06 09:16
Robin, already did that, but problem persists.

In fact that was the startingpoint, i put in the code to get some
additional info

Op ma 6 nov. 2017 om 10:07 schreef Robin Bolscher <notifications@github.com>

**Comment by RobinBol** [comment] 2017-11-06 09:18
Ok, well, but then at least change it back, because this will not work and will probably make the hunt for a bug more difficult!

If you publish the code such as it should work and let me know what the problem is exactly (with some logs) I might find something.

**Comment by kasteleman** [comment] 2017-11-06 09:22
Ok, i wil do that this evening.
Also get the message of to many listeners.

Op ma 6 nov. 2017 om 10:18 schreef Robin Bolscher <notifications@github.com>

**Comment by RobinBol** [comment] 2017-11-06 09:22
Ok, that is just a warning that occurs when you have more than 11 drivers I think.

**Comment by kasteleman** [comment] 2017-11-06 09:24
More then 10, because currently it is 11
Bas mentioned it can be adjusted within Homey, so we don’t get this message

Op ma 6 nov. 2017 om 10:22 schreef Robin Bolscher <notifications@github.com>

**Comment by kasteleman** [comment] 2017-11-07 18:49
The problem with the tunable bulb isn't occurring anymore. I think it was another problem with my zigbee that caused this and troubled my mind. But another question arises:

The super.onMeshInit() can be used with ZigBeeLightDevice.js, but not with ZigBeeDevice.js
Is that as by design?

**Comment by RobinBol** [comment] 2017-11-08 11:01
That is how the inheritance works (as explained on Slack), will close this issue as it seems to be resolved!

**Closed by RobinBol** 2017-11-08 11:01 UTC
Labels: bug
